FROM python:3.10-slim

WORKDIR /app

ENV PYTHONPATH=/app
ENV MLFLOW_TRACKING_URI=http://mlflow:5000

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc make && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "src/experiments/train_mlflow.py"]
