FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc make && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir mlflow==3.1.0 \
    tensorflow-cpu==2.19.0 \
    keras==3.10.0 \
    numpy==2.1.3

EXPOSE 5000

ENTRYPOINT ["mlflow"]

CMD ["models", "serve", "-m", "models:/solana_lstm_model/1", "--no-conda", "--host", "0.0.0.0", "--port", "5000"]
