services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: solana_mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow ui --host 0.0.0.0 --port 5000

  init-train:
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: solana_init_train
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./data:/app/data

  mlflow-serving:
    build:
      context: .
      dockerfile: Dockerfile.mlflow-serving
    container_name: solana_mlflow_serving
    ports:
      - "5001:5000"
    depends_on:
      - init-train
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlruns:/mlflow/mlruns

  solana-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: solana_api
    ports:
      - "9696:9696"
    depends_on:
      - mlflow-serving
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - .:/app
